//! Rendering helpers for export output: markdown and JSON.

use std::path::Path;

use serde_json::json;

use crate::surface::card::{FileCard, SymbolCard};

use super::ExportDecision;

const GENERATED_HEADER: &str = "\
<!-- This file is generated by `synrepo export`. Do not edit manually.
     Re-generate with: synrepo export
     To commit this file, pass --commit to suppress .gitignore insertion.
-->\n\n";

/// Write one markdown file per card type to `export_dir`.
pub fn write_markdown(
    export_dir: &Path,
    file_cards: &[FileCard],
    symbol_cards: &[SymbolCard],
    decisions: &[ExportDecision],
) -> crate::Result<()> {
    write_files_md(export_dir, file_cards)?;
    write_symbols_md(export_dir, symbol_cards)?;
    write_decisions_md(export_dir, decisions)?;
    Ok(())
}

fn write_files_md(export_dir: &Path, cards: &[FileCard]) -> crate::Result<()> {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("# Files\n\n");
    for card in cards {
        out.push_str(&format!("## `{}`\n\n", card.path));
        out.push_str(&format!("- **Symbols**: {}\n", card.symbols.len()));
        out.push_str(&format!("- **Imports**: {}\n", card.imports.len()));
        out.push_str(&format!("- **Imported by**: {}\n", card.imported_by.len()));
        if let Some(flag) = &card.drift_flag {
            out.push_str(&format!("- **Drift**: {flag}\n"));
        }
        out.push('\n');
    }
    std::fs::write(export_dir.join("files.md"), out.as_bytes())?;
    Ok(())
}

fn write_symbols_md(export_dir: &Path, cards: &[SymbolCard]) -> crate::Result<()> {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("# Symbols\n\n");
    for card in cards {
        out.push_str(&format!("## `{}`\n\n", card.qualified_name));
        out.push_str(&format!("- **Defined at**: `{}`\n", card.defined_at));
        if let Some(sig) = &card.signature {
            out.push_str(&format!("- **Signature**: `{sig}`\n"));
        }
        if let Some(doc) = &card.doc_comment {
            let preview: String = doc.lines().next().unwrap_or_default().to_string();
            if !preview.is_empty() {
                out.push_str(&format!("- **Doc**: {preview}\n"));
            }
        }
        out.push('\n');
    }
    std::fs::write(export_dir.join("symbols.md"), out.as_bytes())?;
    Ok(())
}

fn write_decisions_md(export_dir: &Path, decisions: &[ExportDecision]) -> crate::Result<()> {
    let mut out = String::from(GENERATED_HEADER);
    out.push_str("# Decisions\n\n");
    for d in decisions {
        out.push_str(&format!("## {}\n\n", d.title));
        out.push_str(&format!("- **Source**: `{}`\n", d.path));
        if let Some(status) = &d.status {
            out.push_str(&format!("- **Status**: {status}\n"));
        }
        if let Some(summary) = &d.summary {
            out.push_str(&format!("\n{summary}\n"));
        }
        if let Some(body) = &d.decision_body {
            out.push_str(&format!("\n{body}\n"));
        }
        out.push('\n');
    }
    std::fs::write(export_dir.join("decisions.md"), out.as_bytes())?;
    Ok(())
}

/// Write a single `index.json` with all card arrays keyed by type.
/// Note: ChangeRiskCard is computed on-demand via `synrepo change-risk` CLI or
/// MCP tool and is not pre-computed in exports (requires query against graph).
pub fn write_json(
    export_dir: &Path,
    file_cards: &[FileCard],
    symbol_cards: &[SymbolCard],
    decisions: &[ExportDecision],
) -> crate::Result<()> {
    let index = json!({
        "generated_note": "Generated by `synrepo export`. Do not use as synthesis input.",
        "change_risk": {
            "available": true,
            "usage": "Use `synrepo change-risk <target>` CLI or `synrepo_change_risk` MCP tool",
            "note": "ChangeRiskCard is computed on-demand, not pre-computed in exports"
        },
        "files": file_cards,
        "symbols": symbol_cards,
        "decisions": decisions,
    });
    let json_str = serde_json::to_string_pretty(&index)
        .map_err(|e| crate::Error::Other(anyhow::anyhow!("JSON serialization failed: {e}")))?;
    std::fs::write(export_dir.join("index.json"), json_str.as_bytes())?;
    Ok(())
}
