use std::collections::HashMap;
use std::io::Write;

use serde::ser::{Error as SerError, SerializeSeq, SerializeStruct};
use serde::{Serialize, Serializer};

use crate::{
    core::ids::{ConceptNodeId, EdgeId, FileNodeId, SymbolNodeId},
    store::compatibility::GRAPH_FORMAT_VERSION,
    structure::graph::{Edge, GraphReader},
    surface::card::Budget,
};

use super::types::{concept_node, export_edge, file_node, summarize_edges, symbol_node};
use super::{types::GraphCounts, types::GraphDegree, GraphExportStats};

const GRAPH_EXPORT_SCHEMA_VERSION: u32 = 1;
const GENERATED_NOTE: &str =
    "Generated by `synrepo export`. Convenience output only; not graph truth or explain input.";

pub(super) const GRAPH_EXPORT_BATCH_SIZE: usize = 512;

pub(super) struct GraphExportContext<'a> {
    graph: &'a dyn GraphReader,
    budget: Budget,
    file_ids: Vec<FileNodeId>,
    symbol_ids: Vec<SymbolNodeId>,
    concept_ids: Vec<ConceptNodeId>,
    edges: Vec<Edge>,
    drift_scores: HashMap<EdgeId, f32>,
    degree_by_node: HashMap<String, GraphDegree>,
    counts: GraphCounts,
}

impl<'a> GraphExportContext<'a> {
    pub(super) fn load(graph: &'a dyn GraphReader, budget: Budget) -> crate::Result<Self> {
        let mut file_paths = graph.all_file_paths()?;
        file_paths.sort_by(|(a_path, a_id), (b_path, b_id)| {
            a_path.cmp(b_path).then_with(|| a_id.cmp(b_id))
        });
        let file_ids = file_paths.into_iter().map(|(_, id)| id).collect::<Vec<_>>();

        let mut symbol_names = graph.all_symbol_names()?;
        symbol_names.sort_by(|(a_id, _, a_name), (b_id, _, b_name)| {
            a_name.cmp(b_name).then_with(|| a_id.cmp(b_id))
        });
        let symbol_ids = symbol_names
            .into_iter()
            .map(|(id, _, _)| id)
            .collect::<Vec<_>>();

        let mut concept_paths = graph.all_concept_paths()?;
        concept_paths.sort_by(|(a_path, a_id), (b_path, b_id)| {
            a_path.cmp(b_path).then_with(|| a_id.cmp(b_id))
        });
        let concept_ids = concept_paths
            .into_iter()
            .map(|(_, id)| id)
            .collect::<Vec<_>>();

        let edges = graph.all_edges()?;
        let drift_scores = current_drift_scores(graph)?;
        let (degree_by_node, edges_by_kind) = summarize_edges(&edges);
        let counts = GraphCounts {
            nodes: file_ids.len() + symbol_ids.len() + concept_ids.len(),
            edges: edges.len(),
            files: file_ids.len(),
            symbols: symbol_ids.len(),
            concepts: concept_ids.len(),
            edges_by_kind,
        };

        Ok(Self {
            graph,
            budget,
            file_ids,
            symbol_ids,
            concept_ids,
            edges,
            drift_scores,
            degree_by_node,
            counts,
        })
    }

    pub(super) fn stats(&self) -> GraphExportStats {
        GraphExportStats {
            node_count: self.counts.nodes,
            edge_count: self.counts.edges,
        }
    }

    pub(super) fn write_pretty_json<W: Write + ?Sized>(&self, writer: &mut W) -> crate::Result<()> {
        self.write_json(writer, true, "graph JSON")
    }

    pub(super) fn write_compact_json<W: Write + ?Sized>(
        &self,
        writer: &mut W,
    ) -> crate::Result<()> {
        self.write_json(writer, false, "graph HTML data")
    }

    fn write_json<W: Write + ?Sized>(
        &self,
        writer: &mut W,
        pretty: bool,
        label: &str,
    ) -> crate::Result<()> {
        let payload = GraphExportPayload { context: self };
        let result = if pretty {
            serde_json::to_writer_pretty(&mut *writer, &payload)
        } else {
            serde_json::to_writer(&mut *writer, &payload)
        };
        result.map_err(|e| crate::Error::Other(anyhow::anyhow!("{label} serialize failed: {e}")))
    }
}

struct GraphExportPayload<'a, 'g> {
    context: &'a GraphExportContext<'g>,
}

impl Serialize for GraphExportPayload<'_, '_> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut state = serializer.serialize_struct("GraphExport", 7)?;
        state.serialize_field("generated_note", GENERATED_NOTE)?;
        state.serialize_field("schema_version", &GRAPH_EXPORT_SCHEMA_VERSION)?;
        state.serialize_field("graph_schema_version", &GRAPH_FORMAT_VERSION)?;
        state.serialize_field("budget", budget_label(self.context.budget))?;
        state.serialize_field("counts", &self.context.counts)?;
        state.serialize_field(
            "nodes",
            &GraphExportNodes {
                context: self.context,
            },
        )?;
        state.serialize_field(
            "edges",
            &GraphExportEdges {
                context: self.context,
            },
        )?;
        state.end()
    }
}

struct GraphExportNodes<'a, 'g> {
    context: &'a GraphExportContext<'g>,
}

impl Serialize for GraphExportNodes<'_, '_> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut seq = serializer.serialize_seq(Some(self.context.counts.nodes))?;
        self.serialize_files(&mut seq)?;
        self.serialize_symbols(&mut seq)?;
        self.serialize_concepts(&mut seq)?;
        seq.end()
    }
}

impl GraphExportNodes<'_, '_> {
    fn serialize_files<S>(&self, seq: &mut S) -> Result<(), S::Error>
    where
        S: SerializeSeq,
    {
        for ids in self.context.file_ids.chunks(GRAPH_EXPORT_BATCH_SIZE) {
            let order = ids
                .iter()
                .enumerate()
                .map(|(index, id)| (*id, index))
                .collect::<HashMap<_, _>>();
            let mut files = self
                .context
                .graph
                .get_files(ids)
                .map_err(S::Error::custom)?;
            files.sort_by_key(|file| order.get(&file.id).copied().unwrap_or(usize::MAX));
            for file in files {
                seq.serialize_element(&file_node(
                    file,
                    self.context.budget,
                    &self.context.degree_by_node,
                ))?;
            }
        }
        Ok(())
    }

    fn serialize_symbols<S>(&self, seq: &mut S) -> Result<(), S::Error>
    where
        S: SerializeSeq,
    {
        for ids in self.context.symbol_ids.chunks(GRAPH_EXPORT_BATCH_SIZE) {
            let order = ids
                .iter()
                .enumerate()
                .map(|(index, id)| (*id, index))
                .collect::<HashMap<_, _>>();
            let mut symbols = self
                .context
                .graph
                .get_symbols(ids)
                .map_err(S::Error::custom)?;
            symbols.sort_by_key(|symbol| order.get(&symbol.id).copied().unwrap_or(usize::MAX));
            for symbol in symbols {
                seq.serialize_element(&symbol_node(
                    symbol,
                    self.context.budget,
                    &self.context.degree_by_node,
                ))?;
            }
        }
        Ok(())
    }

    fn serialize_concepts<S>(&self, seq: &mut S) -> Result<(), S::Error>
    where
        S: SerializeSeq,
    {
        for ids in self.context.concept_ids.chunks(GRAPH_EXPORT_BATCH_SIZE) {
            let order = ids
                .iter()
                .enumerate()
                .map(|(index, id)| (*id, index))
                .collect::<HashMap<_, _>>();
            let mut concepts = self
                .context
                .graph
                .get_concepts(ids)
                .map_err(S::Error::custom)?;
            concepts.sort_by_key(|concept| order.get(&concept.id).copied().unwrap_or(usize::MAX));
            for concept in concepts {
                seq.serialize_element(&concept_node(
                    concept,
                    self.context.budget,
                    &self.context.degree_by_node,
                ))?;
            }
        }
        Ok(())
    }
}

struct GraphExportEdges<'a, 'g> {
    context: &'a GraphExportContext<'g>,
}

impl Serialize for GraphExportEdges<'_, '_> {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        let mut seq = serializer.serialize_seq(Some(self.context.edges.len()))?;
        for edge in &self.context.edges {
            seq.serialize_element(&export_edge(edge, &self.context.drift_scores))?;
        }
        seq.end()
    }
}

fn current_drift_scores(graph: &dyn GraphReader) -> crate::Result<HashMap<EdgeId, f32>> {
    let Some(revision) = graph.latest_drift_revision()? else {
        return Ok(HashMap::new());
    };
    Ok(graph.read_drift_scores(&revision)?.into_iter().collect())
}

fn budget_label(budget: Budget) -> &'static str {
    match budget {
        Budget::Tiny => "tiny",
        Budget::Normal => "normal",
        Budget::Deep => "deep",
    }
}

#[cfg(test)]
mod tests;
