//! On-disk binary format for `FlatVecIndex`.

use std::fs::File;
use std::io::{BufReader, BufWriter, Read, Write};

use super::super::chunk::{ChunkId, EmbeddingChunkSource};
use super::super::model::{EmbeddingSession, ModelResolution};
use super::{ChunkMeta, FlatVecIndex};

/// Current format version for the embedding index.
///
/// Bumped 2 → 3 when `ChunkId` widened from `u64` to `u128`. The on-disk
/// chunk id field is now 16 bytes little-endian instead of 8. There is no
/// in-place migration: the version mismatch error path in [`FlatVecIndex::load`]
/// surfaces a clear rebuild prompt, and the index is regenerated by
/// `synrepo reconcile`.
///
/// Bumped 3 → 4 when symbol chunk text began including path, signature, and
/// doc comments.
///
/// Bumped 4 → 5 when symbol chunk text was capped to the embedding context
/// budget used by local providers such as Ollama.
pub(super) const INDEX_FORMAT_VERSION: u16 = 5;

impl FlatVecIndex {
    /// Save the index to disk.
    pub fn save(&self, path: &std::path::Path) -> crate::Result<()> {
        let mut file = BufWriter::new(File::create(path)?);

        // Write version and metadata length
        file.write_all(&INDEX_FORMAT_VERSION.to_le_bytes())?;
        let metadata_len = self.chunks.len() as u32;
        file.write_all(&metadata_len.to_le_bytes())?;

        // Write dimension and model name
        file.write_all(&self.dim.to_le_bytes())?;
        let model_name_len = self.model_name.len() as u32;
        file.write_all(&model_name_len.to_le_bytes())?;
        file.write_all(self.model_name.as_bytes())?;

        // Write normalization flag
        file.write_all(&[if self.normalized { 1u8 } else { 0u8 }; 1])?;

        // Write chunks
        for meta in &self.chunks {
            file.write_all(&meta.id.0.to_le_bytes())?;
            match &meta.source {
                EmbeddingChunkSource::Symbol { .. } => file.write_all(&[0u8; 1])?,
                EmbeddingChunkSource::Concept { .. } => file.write_all(&[1u8; 1])?,
            }
            let text_len = meta.text.len() as u32;
            file.write_all(&text_len.to_le_bytes())?;
            file.write_all(meta.text.as_bytes())?;
        }

        // Write vectors
        for v in &self.vectors {
            file.write_all(&v.to_le_bytes())?;
        }

        // Explicit flush so a disk-full / IO failure during the final buffered
        // write surfaces here; BufWriter::drop swallows flush errors.
        file.flush()?;
        Ok(())
    }

    /// Load the index from disk.
    pub fn load(path: &std::path::Path, expected_dim: u16) -> crate::Result<Self> {
        let mut file = BufReader::new(File::open(path)?);
        let mut buf4 = [0u8; 4];
        let mut buf2 = [0u8; 2];

        // Read version
        file.read_exact(&mut buf2)?;
        let version = u16::from_le_bytes(buf2);
        if version != INDEX_FORMAT_VERSION {
            return Err(crate::Error::Other(anyhow::anyhow!(
                "Index format version {} is unsupported (expected {})",
                version,
                INDEX_FORMAT_VERSION
            )));
        }

        // Read metadata length
        file.read_exact(&mut buf4)?;
        let metadata_len = u32::from_le_bytes(buf4) as usize;

        // Read dimension
        file.read_exact(&mut buf2)?;
        let dim = u16::from_le_bytes(buf2);
        if dim != expected_dim {
            return Err(crate::Error::Other(anyhow::anyhow!(
                "Index dimension {} does not match expected {}",
                dim,
                expected_dim
            )));
        }

        // Read model name
        file.read_exact(&mut buf4)?;
        let model_name_len = u32::from_le_bytes(buf4) as usize;
        let mut model_name_buf = vec![0u8; model_name_len];
        file.read_exact(&mut model_name_buf)?;
        let model_name = String::from_utf8(model_name_buf)
            .map_err(|e| crate::Error::Other(anyhow::anyhow!("Invalid model name: {}", e)))?;

        // Read normalization flag
        let mut norm_buf = [0u8; 1];
        file.read_exact(&mut norm_buf)?;
        let normalized = norm_buf[0] != 0;

        // Read chunks
        let mut chunks = Vec::with_capacity(metadata_len);
        let mut buf16 = [0u8; 16];
        for _ in 0..metadata_len {
            file.read_exact(&mut buf16)?;
            let chunk_id = u128::from_le_bytes(buf16);

            let mut variant_tag = [0u8; 1];
            file.read_exact(&mut variant_tag)?;

            file.read_exact(&mut buf4)?;
            let text_len = u32::from_le_bytes(buf4) as usize;
            let mut text_buf = vec![0u8; text_len];
            file.read_exact(&mut text_buf)?;
            let text = String::from_utf8(text_buf)
                .map_err(|e| crate::Error::Other(anyhow::anyhow!("Invalid chunk text: {}", e)))?;

            let source = if variant_tag[0] == 0 {
                EmbeddingChunkSource::Symbol {
                    id: crate::core::ids::SymbolNodeId(chunk_id),
                    file_id: crate::core::ids::FileNodeId(0),
                    qualified_name: text.clone(),
                    kind_label: String::new(),
                }
            } else {
                EmbeddingChunkSource::Concept {
                    id: crate::core::ids::ConceptNodeId(chunk_id),
                    path: text.clone(),
                }
            };

            chunks.push(ChunkMeta {
                id: ChunkId(chunk_id),
                source,
                text,
            });
        }

        // Read vectors
        let vector_len = metadata_len * dim as usize;
        let mut vectors = vec![0f32; vector_len];
        for v in &mut vectors {
            let mut bits = [0u8; 4];
            file.read_exact(&mut bits)?;
            *v = f32::from_le_bytes(bits);
        }

        Ok(Self {
            dim,
            model_name,
            format_version: version,
            normalized,
            chunks,
            vectors,
            session: None,
        })
    }

    /// Load the index and restore the embedding session from a model resolution.
    pub fn load_with_resolution(
        path: &std::path::Path,
        expected_dim: u16,
        model_res: &ModelResolution,
    ) -> crate::Result<Self> {
        let mut index = Self::load(path, expected_dim)?;
        index.session = Some(EmbeddingSession::new_from_resolution(model_res)?);
        Ok(index)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn persistence_v3_round_trip() -> crate::Result<()> {
        let index = FlatVecIndex {
            dim: 384,
            model_name: "test-model".into(),
            format_version: INDEX_FORMAT_VERSION,
            normalized: true,
            chunks: vec![ChunkMeta {
                id: ChunkId(1),
                source: EmbeddingChunkSource::Symbol {
                    id: crate::core::ids::SymbolNodeId(1),
                    file_id: crate::core::ids::FileNodeId(1),
                    qualified_name: "test::func".into(),
                    kind_label: "function".into(),
                },
                text: "test::func function".into(),
            }],
            vectors: vec![0.1f32; 384],
            session: None,
        };

        let temp_dir = tempfile::tempdir()?;
        let path = temp_dir.path().join("index.bin");
        index.save(&path)?;

        let loaded = FlatVecIndex::load(&path, 384)?;
        assert_eq!(loaded.format_version, INDEX_FORMAT_VERSION);
        assert!(loaded.normalized);
        assert_eq!(loaded.model_name, "test-model");
        assert_eq!(loaded.len(), 1);

        Ok(())
    }

    #[test]
    fn load_rejects_mismatched_expected_dim() -> crate::Result<()> {
        let index = FlatVecIndex {
            dim: 384,
            model_name: "test-model".into(),
            format_version: INDEX_FORMAT_VERSION,
            normalized: true,
            chunks: vec![],
            vectors: vec![],
            session: None,
        };
        let temp_dir = tempfile::tempdir()?;
        let path = temp_dir.path().join("index.bin");
        index.save(&path)?;

        let err = FlatVecIndex::load(&path, 768).unwrap_err();
        let msg = err.to_string();
        assert!(
            msg.contains("does not match expected"),
            "expected dim-mismatch error, got: {msg}"
        );
        Ok(())
    }
}
